// Even Fibonacci numbers
// Problem 2 
// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

class EvenFibbonaci {


    fibo(){

        let b = 1;
        let c = 2, d;
        let sum = 0;

            while(c < 4000000) {
                    sum += c;
                    d = b+(c<<0x01);
                    c = d+b+c;
                    b = d;
            }           
        
        // console.log(sum)
        return sum;
    }

}

var Efb = new EvenFibbonaci
console.log(Efb.fibo())


//  https://stackoverflow.com/a/24483426

